apiVersion: apps/v1
kind: Deployment
metadata:
  name: Canopus-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Canopus-api
  template:
    metadata:
      labels:
        app: Canopus-api
    spec:
      containers:
      - name: Canopus
        image: your-username/Canopus:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: Canopus-secrets
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: Canopus-secrets
              key: secret-key
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
